#!/usr/bin/env node
'use strict';
var commandLine = require('./lib/commandLine').parse(),
    commandPath = './commands/' + commandLine.command;

try{
    require.resolve(commandPath);
}catch(e){
    commandPath = './commands/help';
}

require(commandPath)(commandLine.args);